// 主流程端到端测试：安装 → 对话（分支 / 对比 / 知识库 / 工具）→ 图像生成与编辑 → 作品集 → 短片项目 → 多用户与配额。
// 各步骤依赖前一步的数据，按顺序在同一个浏览器页面中执行。
import { expect, test } from '@playwright/test'

test.describe.configure({ mode: 'serial' })

/** @type {import('@playwright/test').Page} */
let page
const errors = []

// 回复结束：停止按钮消失、发送按钮重新出现
const composerIdle = () => expect(page.locator('.composer .send-btn')).toBeVisible({ timeout: 60_000 })
const tasksIdle = () => expect.poll(async () => (await (await page.request.get('/api/tasks?status=active')).json()).length, { timeout: 60_000 }).toBe(0)
const md = (name, text) => ({ name, mimeType: 'text/markdown', buffer: Buffer.from(text) })

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage()
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
  page.on('console', (m) => {
    if (m.type() === 'error' && !/status of 4(01|03|29)/.test(m.text())) errors.push(`console: ${m.text()}`)
  })
})

test.afterAll(async () => {
  await page.close()
})

test('安装向导', async () => {
  await page.goto('/')
  await page.waitForURL('**/install')
  const pw = page.locator('input[type=password]')
  await pw.nth(0).fill('password123')
  await pw.nth(1).fill('password123')
  await page.click('button:has-text("下一步")')
  await page.click('button.preset:has-text("OpenAI")')
  await page.fill('input[placeholder="https://api.openai.com/v1"]', 'http://127.0.0.1:9001/v1')
  await page.fill('input[placeholder="sk-..."]', 'sk-mock-123456')
  await page.click('button:has-text("获取模型列表")')
  await expect(page.locator('.result.ok')).toBeVisible()
  await page.click('button:has-text("自动分类填入")')
  await page.click('button:has-text("完成安装")')
  await page.click('button:has-text("进入创作台")')
  await expect(page.locator('.hero')).toBeVisible()
})

test('对话：流式回复、重新生成分支与切换', async () => {
  await page.goto('/chat')
  await page.click('button:has-text("新对话")')
  await page.fill('.composer textarea', '问题一')
  await page.keyboard.press('Enter')
  await composerIdle()
  await expect(page.locator('.msg.assistant .md')).toContainText('问题一')
  const reply = page.locator('.msg.assistant').last()
  await reply.hover()
  await reply.locator('.ops button').nth(1).click()
  await composerIdle()
  await page.locator('.msg.assistant').last().hover()
  await expect(page.locator('.msg.assistant').last().locator('.branch-nav span')).toHaveText('2 / 2')
  await page.locator('.msg.assistant').last().locator('.branch-nav button').first().click()
  await expect(page.locator('.msg.assistant').last().locator('.branch-nav span')).toHaveText('1 / 2')
})

test('对话：多模型对比', async () => {
  await page.click('button:has-text("多模型对比")')
  await page.click('.compare-pop .n-base-selection')
  await page.click('.n-base-select-option:has-text("gpt-4o")')
  await page.click('.n-base-select-option:has-text("deepseek-reasoner")')
  await page.mouse.click(700, 200)
  await page.fill('.composer textarea', '写一句广告语')
  await page.keyboard.press('Enter')
  await composerIdle()
  await expect(page.locator('.compare .compare-col')).toHaveCount(2)
  await page.locator('.compare-col').nth(1).locator('button:has-text("选用")').click()
  await expect(page.locator('.compare-col').nth(1)).toHaveClass(/chosen/)
  await page.click('button:has-text("对比 2 个模型")')
  await page.click('.compare-pop button:has-text("关闭对比")')
  await page.mouse.click(700, 200)
})

test('知识库：上传文档并在对话中引用', async () => {
  await page.goto('/knowledge')
  await page.click('button:has-text("新建知识库")')
  await page.fill('.n-modal input[placeholder="例如：品牌资料"]', '产品手册')
  await page.click('.n-modal button:has-text("保存")')
  await page.setInputFiles('.drop input[type=file]', md('手册.md', 'PWD 是一个个人 AIGC 创作平台。\n\n部署方式是 Docker，镜像发布在 GHCR。'))
  await expect(page.locator('td .n-tag:has-text("已就绪")')).toBeVisible()
  await page.goto('/chat')
  await page.click('button:has-text("新对话")')
  await page.click('.tool-btn:has-text("知识库")')
  await page.click('.pick-pop .n-checkbox:has-text("产品手册")')
  await page.mouse.click(700, 200)
  await page.fill('.composer textarea', 'PWD 怎么部署？')
  await page.keyboard.press('Enter')
  await composerIdle()
  await expect(page.locator('.msg.assistant .src:has-text("手册.md")')).toBeVisible()
})

test('对话：工具调用生成图片', async () => {
  await page.click('button:has-text("新对话")')
  await page.click('.tool-btn:has-text("工具")')
  await page.click('.tools-pop .n-checkbox:has-text("生成图片")')
  await page.mouse.click(700, 200)
  await page.fill('.composer textarea', '帮我画一只猫')
  await page.keyboard.press('Enter')
  await composerIdle()
  await expect(page.locator('.tool-call:has-text("生成图片") .tool-assets img')).toBeVisible()
})

test('图像：生成、局部重绘与本地放大', async () => {
  await page.goto('/image')
  await page.fill('.prompt-input textarea', '一只橘猫')
  await page.click('.panel-foot button')
  await expect(page.locator('.result.image img').first()).toBeVisible()
  await page.goto('/gallery')
  await page.locator('.tile').first().click()
  await page.click('button:has-text("编辑图片")')
  await page.click('.n-dropdown-option:has-text("局部重绘")')
  const box = await page.locator('.canvas-box canvas').boundingBox()
  await page.mouse.move(box.x + box.width * 0.3, box.y + box.height * 0.3)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width * 0.6, box.y + box.height * 0.5, { steps: 6 })
  await page.mouse.up()
  await page.fill('.ed-panel textarea', '一顶红色帽子')
  await page.click('.ed-actions button')
  await expect(page.locator('.editor')).toHaveCount(0)
  await page.click('button:has-text("编辑图片")')
  await page.click('.n-dropdown-option:has-text("高清放大")')
  await page.click('.ed-actions button')
  await expect(page.locator('.editor')).toHaveCount(0)
  await tasksIdle()
  const tasks = await (await page.request.get('/api/tasks?limit=5')).json()
  expect(tasks.every((t) => t.status === 'succeeded')).toBeTruthy()
  await page.keyboard.press('Escape')
})

test('作品集', async () => {
  await page.goto('/gallery')
  await page.click('button:has-text("多选")')
  await page.locator('.tile').nth(0).click()
  await page.locator('.tile').nth(1).click()
  await page.click('button:has-text("移到作品集")')
  await page.click('.n-dropdown-option:has-text("新建作品集")')
  await page.fill('.n-dialog input', '猫咪系列')
  await page.click('.n-dialog button:has-text("保存")')
  await expect(page.locator('.board:has-text("猫咪系列") .bcount')).toHaveText('2')
})

test('短片项目：剧本 → 角色 → 分镜 → 关键帧', async () => {
  await page.goto('/projects')
  await page.click('button:has-text("新建项目")')
  await page.fill('.n-modal input[placeholder="例如：小橘的午后"]', '小橘的午后')
  await page.fill('.n-modal textarea', '一只橘猫在午后的窗台上，被一只蝴蝶吸引')
  await page.click('.n-modal button:has-text("创建")')
  await page.click('button:has-text("AI 写剧本")')
  await expect(page.locator('.script textarea')).toHaveValue(/旁白/)
  await page.click('.st:has-text("角色与场景")')
  await page.click('button:has-text("从剧本提取")')
  await expect(page.locator('.el-card')).toHaveCount(2)
  await page.click('.st:has-text("分镜")')
  await page.click('button:has-text("AI 拆分镜")')
  await expect(page.locator('.shot')).toHaveCount(3)
  await page.click('.toolbar button:has-text("关键帧")')
  await expect(page.locator('.shot .media-box img')).toHaveCount(3, { timeout: 30_000 })
})

test('多用户：用户组配额', async () => {
  await page.goto('/users')
  await page.click('.n-tabs-tab:has-text("用户组")')
  await page.click('button:has-text("新建用户组")')
  await page.fill('.n-modal input[placeholder="例如：体验组"]', '体验组')
  await page.locator('.quota-grid label:has-text("每日对话条数") input').fill('1')
  await page.click('.n-modal button:has-text("保存")')
  await page.click('.card:has-text("体验组") button:has-text("设为新用户默认")')
  await page.locator('.n-tabs-tab').first().click()
  await page.click('button:has-text("添加用户")')
  await page.fill('.n-modal input[placeholder^="2～32"]', 'bob')
  await page.fill('.n-modal input[type=password]', 'bobpass123')
  await page.click('.n-modal button:has-text("创建")')
  await expect(page.locator('tr:has-text("bob")')).toContainText('体验组')

  await page.request.post('/api/auth/logout')
  await page.goto('/login')
  await page.fill('input[autocomplete=username]', 'bob')
  await page.fill('input[autocomplete=current-password]', 'bobpass123')
  await page.keyboard.press('Enter')
  await expect(page.locator('.hero')).toBeVisible()
  await page.goto('/chat')
  await page.click('button:has-text("新对话")')
  await page.fill('.composer textarea', '你好')
  await page.keyboard.press('Enter')
  await composerIdle()
  await page.fill('.composer textarea', '再来一条')
  await page.keyboard.press('Enter')
  await expect(page.locator('.msg-error').last()).toContainText('今日对话额度已用完')
})

test('没有前端报错', async () => {
  expect(errors).toEqual([])
})
